# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.10-alpine

# Системные зависимости (нужны для Pillow/cryptography и т.п.)
RUN apk add --no-cache gcc musl-dev libffi-dev

# Рабочая директория
WORKDIR /app

# Копируем код
COPY . .

# Python-зависимости
RUN pip install --no-cache-dir -r requirements.txt

# Открываем порт приложения внутри контейнера
EXPOSE 8000

# ВАЖНО: запускаем MCP-сервер в HTTP-режиме
ENTRYPOINT ["python", "ppt_mcp_server.py", "--transport", "http", "--port", "8000"]
